### PR TITLE
Fix shared preload libraries

### PR DESCRIPTION
**Pull request by 0xfeedface**

### CODE REVIEW

**Comment by sdressler** [comment]
Out of curiosity: which error message did this cause?

**Comment by 0xfeedface** [comment]
Quoting form an email:

> Recreating postgresql-12-swarm64da ... done
> Attaching to postgresql-12-swarm64da
> postgresql-12-swarm64da | Updating config: autovacuum = off ... replaced
> postgresql-12-swarm64da | Updating config: default_statistics_target = 2500 ... replaced
> postgresql-12-swarm64da | Updating config: effective_cache_size = 384GB ... replaced
> postgresql-12-swarm64da | Updating config: enable_material = off ... replaced
> postgresql-12-swarm64da | Updating config: enable_nestloop = off ... replaced
> postgresql-12-swarm64da | Updating config: jit = on ... replaced
> postgresql-12-swarm64da | Updating config: maintenance_work_mem = 16GB ... replaced
> postgresql-12-swarm64da | Updating config: max_connections = 1000 ... replaced
> postgresql-12-swarm64da | Updating config: max_locks_per_transaction = 128 ... replaced
> postgresql-12-swarm64da | Updating config: max_parallel_workers = 1000 ... replaced
> postgresql-12-swarm64da | Updating config: max_parallel_workers_per_gather = 52 ... replaced
> postgresql-12-swarm64da | Updating config: max_stack_depth = 7MB ... replaced
> postgresql-12-swarm64da | Updating config: max_wal_size = 10GB ... replaced
> postgresql-12-swarm64da | Updating config: max_worker_processes = 1024 ... replaced
> postgresql-12-swarm64da | Updating config: min_parallel_table_scan_size = 0 ... replaced
> postgresql-12-swarm64da | Updating config: parallel_leader_participation = off ... replaced
> postgresql-12-swarm64da | Updating config: parallel_setup_cost = 500.0 ... replaced
> postgresql-12-swarm64da | Updating config: parallel_tuple_cost = 0.01 ... replaced
> postgresql-12-swarm64da | Updating config: random_page_cost = 2.0 ... replaced
> postgresql-12-swarm64da | Updating config: seq_page_cost = 1.0 ... replaced
> postgresql-12-swarm64da | Updating config: shared_buffers = 32GB ... replaced
> postgresql-12-swarm64da | Updating config: shared_preload_libraries = swarm64da.so ... replaced
> postgresql-12-swarm64da | Updating config: swarm64da.cost_scan_page = 0.001 ... inserted
> postgresql-12-swarm64da | Updating config: swarm64da.maximize_parallel_workers_per_query = on ... inserted
> postgresql-12-swarm64da | Updating config: work_mem = 6GB ... replaced
> postgresql-12-swarm64da | The files belonging to this database system will be owned by user "postgres".
> postgresql-12-swarm64da | This user must also own the server process.
> postgresql-12-swarm64da |
> postgresql-12-swarm64da | The database cluster will be initialized with locale "en_US.UTF-8".
> postgresql-12-swarm64da | The default database encoding has accordingly been set to "UTF8".
> postgresql-12-swarm64da | The default text search configuration will be set to "english".
> postgresql-12-swarm64da |
> postgresql-12-swarm64da | Data page checksums are disabled.
> postgresql-12-swarm64da |
> postgresql-12-swarm64da | fixing permissions on existing directory /data ... ok
> postgresql-12-swarm64da | creating subdirectories ... ok
> postgresql-12-swarm64da | selecting dynamic shared memory implementation ... posix
> postgresql-12-swarm64da | selecting default max_connections ... 100
> postgresql-12-swarm64da | selecting default shared_buffers ... 128MB
> postgresql-12-swarm64da | selecting default time zone ... Etc/UTC
> postgresql-12-swarm64da | creating configuration files ... ok
> postgresql-12-swarm64da | running bootstrap script ... 2020-10-07 10:11:21.721 GMT [175] LOG:  syntax error in file "/data/postgresql.conf" line 676, near token "swarm64da.so"
> postgresql-12-swarm64da | 2020-10-07 10:11:21.721 GMT [175] LOG:  syntax error in file "/data/postgresql.conf" line 751, near token "swarm64da.so"
> postgresql-12-swarm64da | 2020-10-07 10:11:21.721 GMT [175] FATAL:  configuration file "/data/postgresql.conf" contains errors
> postgresql-12-swarm64da | child process exited with exit code 1
> postgresql-12-swarm64da | initdb: removing contents of data directory "/data"
> 
> postgresql-12-swarm64da exited with code 1

**Comment by sdressler** [comment]
Interesting, my go-to solution was to use `"'swarm64da.so'"`. Thought this was some change in docker-compose.

**Review by sdressler — APPROVED** [review]

**Comment by 0xfeedface** [comment]
According to PostgreSQL docs you should write it without suffix: https://www.postgresql.org/docs/11/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-PRELOAD

But it apparently also works with suffix. Do you think docker-compse is checking the config itself?

**Comment by sdressler** [comment]
No, our docker-compose does not do a check, but IMO the way these variables are handled in `init.sh` now require double quotes sometimes. I have seen the same error with e.g. log configs like `%a %b %c` when setting fields.

**Comment by 0xfeedface** [comment]
Ok, I just tested it. With double quotes it doesn't work, without ".so" it does work. I suspect the bootstrap script in the container. Is that from us?

**Comment by sdressler** [comment]
`init.sh` is from us and then it calls the one from PG which might be not the most recent one.

**Comment by 0xfeedface** [comment]
Ok, our config patching ignores quotes (from within the container):
```
root@bc0c91423813:/# grep preload /data/postgresql.conf
shared_preload_libraries = swarm64da
#local_preload_libraries = ''
#session_preload_libraries = ''
shared_preload_libraries = swarm64da
```

This is apparently not a problem for simple strings, but for file names you need quotes.

**Review by sdressler — APPROVED** [review]

**Pull request merged**
